/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */



const fs = require('fs');
const path = require('path');

const changelogsDir = path.join(__dirname, 'docs', 'Changelogs');

const changelogFiles = fs.readdirSync(changelogsDir)
  .filter(file => file.endsWith('.md'))
  .map(file => `Changelogs/${file.replace('.md', '')}`)
  .sort((a, b) => {
    const regex = /(\d+)-(\d+)-(\d+)(p\d+)?/; // regex to match the file format
    const matchA = a.match(regex);
    const matchB = b.match(regex);

    if (!matchA || !matchB) return 0; // If regex doesn't match, keep original order

    // Extract parts from matched groups
    const [_, majorA, minorA, patchA, previewA] = matchA;
    const [__, majorB, minorB, patchB, previewB] = matchB;

    // Compare major, minor, and patch versions
    if (majorA !== majorB) return majorA - majorB;
    if (minorA !== minorB) return minorA - minorB;
    if (patchA !== patchB) return patchA - patchB;

    // If both are the same version, check for preview
    if (previewA && !previewB) return -1; // A is a preview, B is not
    if (!previewA && previewB) return 1; // B is a preview, A is not

    return 0; // Both are the same version
  })
  .reverse();

const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //versionSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  versionSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Changelogs',
      items: changelogFiles, // Add the list of changelog files here
    },
  ],

};

export default sidebars;
